#!/usr/bin/env bash
# Creating a backup for the server

# Get the MySQL root password as argument
MYSQL_PASSWORD="$1"

# Get the current date in the specified format
DATE_FORMAT=$(date +"%d-%m-%Y")

# Construct the filename for the backup archive
FILE_NAME="$DATE_FORMAT.tar.gz"

# Dump all databases to backup.sql
mysqldump --all-databases -u root --password="$MYSQL_PASSWORD" > backup.sql

# Compress backup.sql into a tar.gz archive with the specified filename
tar -czvf "$FILE_NAME" backup.sql