#!/usr/bin/env bash
# Y U no love me-killer
sudo bash -c "echo $$ > /var/run/myscript.pid"
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/myscript.pid; echo I hate the kill command; exit" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2

done