#!/usr/bin/env bash
# This script is displaying content of the current directory

for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        display_name=$(echo "$file" | cut -d'-' -f2-)
        echo "$display_name"
    fi
done
